/** Declaration file generated by dts-gen */

export = express_csp_header;

declare function express_csp_header(params: any): any;

declare namespace express_csp_header {
    const EVAL: string;

    const INLINE: string;

    const NONCE: string;

    const NONE: string;

    const SELF: string;

    const TLD: string;

    const prototype: {
    };

}

